services:
  metricalo-test:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - '.:/app'
    networks:
      - metricalo
    depends_on:
      - rds-mariadb
  rds-mariadb:
    image: 'mariadb:11.4.3'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'metricalo'
      MYSQL_USER: 'metricalo'
      MYSQL_PASSWORD: 'password'
    volumes:
      - 'rds-mariadb:/var/lib/mysql'
    networks:
      - metricalo
networks:
  metricalo:
    driver: bridge
volumes:
  rds-mariadb: